# Generated by Django 4.2.3 on 2023-07-28 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0002_labtestname_user_lab_temporary_labtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_lab_temporary',
            name='Patient_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stor.register_patient'),
        ),
    ]
