# Generated by Django 4.2.3 on 2023-07-28 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0003_user_lab_temporary_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_lab_temporary',
            name='patient_name',
        ),
        migrations.AlterField(
            model_name='labtest',
            name='lab_tase_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stor.labtestname'),
        ),
        migrations.AlterField(
            model_name='user_lab_temporary',
            name='Patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stor.register_patient'),
        ),
    ]
