# Generated by Django 4.2.3 on 2023-07-31 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stor', '0004_remove_user_lab_temporary_patient_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resulut', models.CharField(max_length=1000)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stor.user_lab_temporary')),
            ],
        ),
    ]
